sudo: required
dist: trusty
git:
  depth: 1

branches:
  only:
    - 'master'

language: node_js
node_js:
  - '6'
  - stable

cache:
  directories:
  - $HOME/.npm

addons:
  chrome: stable

matrix:
  fast_finish: true

env:
  matrix:
    - CASE=app/cordova/bootstrap
    - CASE=app/cordova/bootstrap-authentication
    - CASE=app/cordova/ionic
    - CASE=app/cordova/ionic-authentication
    - CASE=app/cordova/material
    - CASE=app/cordova/material-authentication
    - CASE=app/web/bootstrap
    - CASE=app/web/bootstrap-authentication
    - CASE=app/web/ionic
    - CASE=app/web/ionic-authentication
    - CASE=app/web/material
    - CASE=app/web/material-authentication
    - CASE=app/web/raw
    - CASE=app/web/raw-authentication
    - CASE=app/web+cordova/bootstrap-authentication
    - CASE=app/web+cordova/ionic-authentication
    - CASE=app/web+cordova/material-authentication
      NGX_PACKAGE_MANAGER=yarn
    - CASE=addon/simple
      TEST_ADDON=1
    - CASE=addon/advanced
      TEST_ADDON=1

install:
  - npm install -g yarn@latest
  - npm install
  - npm link

before_script:
  - export DBUS_SESSION_BUS_ADDRESS=/dev/null
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm test $CASE
