environment:
  matrix:
#    - nodejs_version: "6"
#    - nodejs_version: "7"
    - nodejs_version: ""

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yo
  - npm install
  - npm link

test_script:
  - node -v
  - npm -v
  - bash -c "npm test"

build: off
