branches:
  only:
    - master

environment:
  nodejs_version: ""

  matrix:
    - CASE: "app/cordova/bootstrap"
    - CASE: "app/cordova/bootstrap-authentication"
    - CASE: "app/cordova/ionic"
    - CASE: "app/cordova/ionic-authentication"
    - CASE: "app/cordova/material"
    - CASE: "app/cordova/material-authentication"
    - CASE: "app/web/bootstrap"
    - CASE: "app/web/bootstrap-authentication"
    - CASE: "app/web/ionic"
    - CASE: "app/web/ionic-authentication"
    - CASE: "app/web/material"
    - CASE: "app/web/material-authentication"
    - CASE: "app/web+cordova/bootstrap-authentication"
    - CASE: "app/web+cordova/ionic-authentication"
    - CASE: "app/web+cordova/material-authentication"
      NGX_PACKAGE_MANAGER: "yarn"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install -g yo yarn@latest
  - npm install
  - npm link

test_script:
  - node -v
  - npm -v
  - npm run lint
  - bash -c "scripts/test.sh $CASE"

build: off
